apiVersion: v1
kind: Service
metadata:
  name: enterprise-system-20260506-155203-ejye864orgrg-service
spec:
  selector:
    app: enterprise-system-20260506-155203-ejye864orgrg
  ports:
  - port: 80
    targetPort: 8000
  type: ClusterIP
